os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - cmd: set PATH=C:\Program Files (x86)\CMake\bin\;%PATH%

clone_folder: C:\projects\openmeeg

platform: x64
configuration: Release

install:
  - "SET PATH=C:\\Miniconda-x64;C:\\Miniconda-x64\\Scripts;C:\\Python27-x64;%PATH%"
  # by default, all script lines are interpreted as batch

environment:
  global:
    deploy_host:
      secure: elpy2/txkSJRwksSCwLehfm3eLDYTAalGUvTGzPlphY=
    deploy_user:
      secure: 2kJCgcedzNy4rFCQbW7PNw==
    deploy_password:
      secure: Cr908GItsFT5Wp0rYB8ExUukZxSu+mgdprFvU4CxmcM=
    deploy_folder:
      secure: Nk+J4yytvUwuRb5wHVAetZ84O90bJ4ZgwYOS9vLec90o09HP+GLvD9DvNbG1q9Q2p
  matrix:
    - lapack: MKL
    - lapack: Other

matrix:
  fast_finish: true

before_build:
    - if %lapack%==MKL ( cmake -P cmake/InstallMKL.cmake )
    - echo ----------- sik ---------
    - type C:/projects/openmeeg/install-mkl.log
    - echo ----------- sik ---------

build_script:

after_build:

before_test:

on_success:

